[package]
name = "planner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.9"
serde = { version = "1.0.145", features = ["derive"] }
itertools = "0.10.5"
petgraph = "0.6.2"